name: MDViewerPlus
options:
  bundleIdPrefix: com.torstenmahr
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "16.0"
  minimumXcodeGenVersion: "2.38"

targets:
  MDViewerPlus:
    type: application
    platform: macOS
    sources:
      - MDViewerPlus
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.torstenmahr.MDViewerPlus
        PRODUCT_NAME: "MDViewer+"
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        INFOPLIST_FILE: MDViewerPlus/Info.plist
        GENERATE_INFOPLIST_FILE: false
        SWIFT_VERSION: "5.9"
        MACOSX_DEPLOYMENT_TARGET: "13.0"
        CODE_SIGN_STYLE: Automatic
      release:
        SWIFT_OPTIMIZATION_LEVEL: "-Osize"
        DEAD_CODE_STRIPPING: true
        STRIP_INSTALLED_PRODUCT: true
        STRIP_SWIFT_SYMBOLS: true
        STRIP_STYLE: "non-global"
