name: MDViewer
options:
  bundleIdPrefix: com.torstenmahr
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "16.0"
  minimumXcodeGenVersion: "2.38"

targets:
  MDViewer:
    type: application
    platform: macOS
    sources:
      - MDViewer
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.torstenmahr.MDViewer
        PRODUCT_NAME: MDViewer
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        INFOPLIST_FILE: MDViewer/Info.plist
        GENERATE_INFOPLIST_FILE: false
        SWIFT_VERSION: "5.9"
        MACOSX_DEPLOYMENT_TARGET: "13.0"
        CODE_SIGN_STYLE: Automatic
