name: MDViewerPlus
options:
  bundleIdPrefix: com.torstenmahr
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "16.0"
  minimumXcodeGenVersion: "2.38"

schemes:
  MDViewerPlus:
    build:
      targets:
        MDViewerPlus: all
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - MDViewerPlusTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

  MDViewerPlusUITests:
    build:
      targets:
        MDViewerPlus: all
    test:
      config: Debug
      targets:
        - MDViewerPlusUITests

targets:
  MDViewerPlus:
    type: application
    platform: macOS
    sources:
      - MDViewerPlus
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.torstenmahr.MDViewerPlus
        PRODUCT_NAME: "MDViewer+"
        PRODUCT_MODULE_NAME: MDViewerPlus
        MARKETING_VERSION: "1.3.1"
        CURRENT_PROJECT_VERSION: "5"
        INFOPLIST_FILE: MDViewerPlus/Info.plist
        GENERATE_INFOPLIST_FILE: false
        SWIFT_VERSION: "5.9"
        MACOSX_DEPLOYMENT_TARGET: "13.0"
        CODE_SIGN_STYLE: Automatic
      configs:
        Release:
          CODE_SIGN_ENTITLEMENTS: MDViewerPlus/MDViewerPlus.entitlements
          ENABLE_APP_SANDBOX: true
          ENABLE_HARDENED_RUNTIME: true
          SWIFT_OPTIMIZATION_LEVEL: "-Osize"
          DEAD_CODE_STRIPPING: true
          STRIP_INSTALLED_PRODUCT: true
          STRIP_SWIFT_SYMBOLS: true
          STRIP_STYLE: "non-global"

  MDViewerPlusTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - MDViewerPlusTests
    dependencies:
      - target: MDViewerPlus
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.torstenmahr.MDViewerPlusTests
        GENERATE_INFOPLIST_FILE: true
        SWIFT_VERSION: "5.9"
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/MDViewer+.app/Contents/MacOS/MDViewer+"
        BUNDLE_LOADER: "$(TEST_HOST)"

  MDViewerPlusUITests:
    type: bundle.ui-testing
    platform: macOS
    sources:
      - MDViewerPlusUITests
    dependencies:
      - target: MDViewerPlus
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.torstenmahr.MDViewerPlusUITests
        GENERATE_INFOPLIST_FILE: true
        SWIFT_VERSION: "5.9"
        TEST_TARGET_NAME: MDViewerPlus
