/*
 * MDViewer+ shared preview renderer.
 *
 * This file is inlined into the render page under the CSP nonce. It owns the
 * generation-aware pipeline used by both editions:
 *
 *   1. safe edition-independent frontmatter separation
 *   2. Markdown parsing with marked + marked-footnote
 *   3. HTML sanitization with the single narrow Markdown DOMPurify policy
 *   4. constrained DOM insertion
 *   5. trusted postprocessors built entirely from DOM APIs
 *   6. optional Full asynchronous rendering with generation cancellation
 *
 * No postprocessor ever parses HTML strings, and the Markdown sanitizer is
 * never widened for highlighter internals or diagram SVG.
 */
(function () {
  "use strict";

  const NONCE = window.__mdviewerNonce;
  const CAPABILITIES = Object.freeze({
    edition: window.__mdviewerEdition === "full" ? "full" : "lite",
    prism: window.__mdviewerEdition !== "full",
    highlightJS: window.__mdviewerEdition === "full",
    frontmatter: window.__mdviewerEdition === "full",
    mermaid: window.__mdviewerEdition === "full",
  });

  const LIMITS = Object.freeze({
    maxHighlightedCodeLength: 200000,
    maxCopyLength: 1000000,
    maxLineNumbers: 5000,
    maxOutlineEntries: 5000,
  });

  const allowedTags = [
    "a", "abbr", "b", "blockquote", "br", "code", "dd", "del", "details",
    "div", "dl", "dt", "em", "h1", "h2", "h3", "h4", "h5", "h6", "hr",
    "i", "img", "input", "kbd", "li", "mark", "ol", "p", "pre", "q",
    "s", "samp", "section", "small", "span", "strong", "sub", "summary",
    "sup", "table", "tbody", "td", "tfoot", "th", "thead", "time", "tr",
    "ul", "var",
  ];
  const allowedAttributes = [
    "align", "alt", "checked", "class", "colspan", "datetime", "disabled", "href",
    "id", "open", "reversed", "rowspan", "src", "start", "title", "type",
    "aria-label", "aria-labelledby", "aria-describedby",
  ];

  const schemePattern = /^[a-z][a-z0-9+.-]*:/i;

  // marked-footnote emits ids/hrefs from this fixed set of prefixes. Anything
  // else generated by user content is dropped so ids stay predictable and no
  // attacker-chosen id can collide with app-owned elements.
  const generatedIdPattern = /^(?:footnote-|footnote-ref-|user-content-)[A-Za-z0-9_-]{1,128}$/;
  const generatedClassPattern = /^(?:footnote|footnotes|footnote-ref|footnote-backref|data-footnotes|sr-only)$/;
  const fragmentPattern = /^#[^\s<>"']{1,512}$/;

  const themeProperties = Object.freeze({
    background: "--color-bg",
    foreground: "--color-fg",
    border: "--color-border",
    codeBackground: "--color-code-bg",
    codeForeground: "--color-code-fg",
    link: "--color-link",
    blockquoteForeground: "--color-blockquote-fg",
    blockquoteBorder: "--color-blockquote-border",
    horizontalRule: "--color-hr",
    selectionBackground: "--color-selection-bg",
    selectionForeground: "--color-selection-fg",
    caret: "--color-caret",
    activeLine: "--color-active-line",
    gutterBackground: "--color-gutter-bg",
    gutterForeground: "--color-gutter-fg",
    splitter: "--color-splitter",
    splitterHover: "--color-splitter-hover",
    searchMatch: "--color-search-match",
    searchMatchSelected: "--color-search-match-selected",
  });
  const trustedColorPattern = /^#[0-9a-f]{6}$/i;

  const ALERT_TYPES = Object.freeze({
    NOTE: { label: "Note", symbol: "i" },
    TIP: { label: "Tip", symbol: "*" },
    IMPORTANT: { label: "Important", symbol: "!" },
    WARNING: { label: "Warning", symbol: "!" },
    CAUTION: { label: "Caution", symbol: "x" },
  });

  const state = {
    generation: 0,
    themeCategory: "light",
    printMode: false,
    outline: [],
    lastMarkdown: "",
  };

  /* ---------------------------------------------------------------- utils */

  function post(channel, payload) {
    const handlers = window.webkit && window.webkit.messageHandlers;
    if (handlers && handlers[channel]) {
      handlers[channel].postMessage(payload);
    }
  }

  function isRelativeURL(value) {
    const trimmed = String(value).trim();
    return (
      trimmed.length > 0 &&
      !trimmed.startsWith("/") &&
      !trimmed.startsWith("//") &&
      !trimmed.startsWith("#") &&
      !schemePattern.test(trimmed)
    );
  }

  function isSafeLink(value) {
    const trimmed = String(value).trim();
    if (trimmed.startsWith("#")) return fragmentPattern.test(trimmed);
    return /^(https?:|mailto:)/i.test(trimmed) || isRelativeURL(trimmed);
  }

  /**
   * The single slug contract shared with the native outline. Kept byte-for-byte
   * equivalent to HeadingSlugger.swift; both sides are covered by tests.
   */
  function slugify(text) {
    let base = "";
    let separator = false;
    for (const character of Array.from(String(text).trim().toLowerCase())) {
      if (/\s/u.test(character)) {
        if (base.length > 0) separator = true;
        continue;
      }
      const codePoint = character.codePointAt(0);
      if (/[a-z0-9_]/u.test(character) || codePoint > 127) {
        if (separator && !base.endsWith("-")) base += "-";
        base += character;
        separator = false;
      } else if (character === "-") {
        if (base.length > 0 && !base.endsWith("-")) base += "-";
        separator = false;
      }
    }
    base = base.replace(/^-+|-+$/g, "");
    return base.length > 0 ? base : "section";
  }

  function uniqueSlug(text, used) {
    const base = slugify(text);
    let candidate = base;
    let counter = 1;
    while (used.has(candidate)) {
      candidate = `${base}-${counter}`;
      counter += 1;
    }
    used.add(candidate);
    return candidate;
  }

  /* ------------------------------------------------------------ sanitizer */

  let hooksInstalled = false;
  let sanitizerMode = "";
  function installMarkdownHooks() {
    if (hooksInstalled) return;
    hooksInstalled = true;

    DOMPurify.addHook("uponSanitizeAttribute", (node, data) => {
      if (sanitizerMode !== "markdown") return;
      const tagName = node.nodeName.toLowerCase();
      const attributeName = data.attrName.toLowerCase();

      if (tagName === "a" && attributeName === "href") {
        data.keepAttr = isSafeLink(data.attrValue);
      } else if (tagName === "img" && attributeName === "src") {
        data.keepAttr = isRelativeURL(data.attrValue);
      } else if (attributeName === "align") {
        const alignment = String(data.attrValue).trim().toLowerCase();
        data.keepAttr =
          (tagName === "th" || tagName === "td") &&
          (alignment === "left" || alignment === "center" || alignment === "right");
        if (data.keepAttr) data.attrValue = alignment;
      } else if (attributeName === "id") {
        data.keepAttr = generatedIdPattern.test(String(data.attrValue));
      } else if (attributeName === "class") {
        // Only the fixed set of footnote classes marked-footnote emits and the
        // language-* hint marked adds to fenced code survive sanitization.
        const classes = String(data.attrValue).trim().split(/\s+/).filter(Boolean);
        const kept = classes.filter(
          (name) =>
            generatedClassPattern.test(name) ||
            /^language-[A-Za-z0-9_+#-]{1,32}$/.test(name)
        );
        if (kept.length === 0) {
          data.keepAttr = false;
        } else {
          data.attrValue = kept.join(" ");
          data.keepAttr = true;
        }
      } else if (
        attributeName === "aria-labelledby" ||
        attributeName === "aria-describedby"
      ) {
        data.keepAttr = generatedIdPattern.test(String(data.attrValue));
      } else if (tagName === "section" && attributeName === "data-footnotes") {
        data.keepAttr = true;
      }
    });
  }

  function sanitizeMarkdownHTML(rawHTML) {
    installMarkdownHooks();
    sanitizerMode = "markdown";
    try {
      return DOMPurify.sanitize(rawHTML, {
        ALLOWED_TAGS: allowedTags,
        ALLOWED_ATTR: allowedAttributes,
        ALLOW_ARIA_ATTR: false,
        ALLOW_DATA_ATTR: false,
        RETURN_DOM_FRAGMENT: true,
      });
    } finally {
      sanitizerMode = "";
    }
  }

  /* ------------------------------------------------------------- markdown */

  let markedConfigured = false;
  function configureMarked() {
    if (markedConfigured) return;
    markedConfigured = true;
    marked.setOptions({ gfm: true, breaks: false });
    if (typeof window.markedFootnote === "function") {
      marked.use(window.markedFootnote());
    }
  }

  function lineBounds(text, start) {
    let contentsEnd = start;
    while (
      contentsEnd < text.length &&
      text[contentsEnd] !== "\r" &&
      text[contentsEnd] !== "\n"
    ) {
      contentsEnd += 1;
    }

    let end = contentsEnd;
    if (text[end] === "\r") {
      end += 1;
      if (text[end] === "\n") end += 1;
    } else if (text[end] === "\n") {
      end += 1;
    }
    return { contentsEnd, end };
  }

  function splitFrontmatter(markdown) {
    const text = String(markdown ?? "");
    const first = lineBounds(text, 0);
    if (text.slice(0, first.contentsEnd) !== "---" || first.end === first.contentsEnd) {
      return null;
    }

    const sourceStart = first.end;
    let lineStart = first.end;
    while (lineStart < text.length) {
      const line = lineBounds(text, lineStart);
      if (text.slice(lineStart, line.contentsEnd) === "---") {
        return {
          source: text.slice(sourceStart, lineStart),
          body: text.slice(line.end),
          bodyUTF16Offset: line.end,
        };
      }
      lineStart = line.end;
    }
    return null;
  }

  function buildRawFrontmatter(source) {
    const pre = document.createElement("pre");
    pre.className = "md-frontmatter-raw";
    const code = document.createElement("code");
    code.textContent = source;
    pre.appendChild(code);
    return pre;
  }

  /* -------------------------------------------------------- postprocessors */

  function decorateHeadings(root) {
    const used = new Set();
    const entries = [];
    const headings = root.querySelectorAll("h1, h2, h3, h4, h5, h6");
    for (const heading of headings) {
      if (entries.length >= LIMITS.maxOutlineEntries) break;
      const title = heading.textContent.trim();
      const slug = uniqueSlug(title, used);
      heading.id = slug;
      entries.push({
        level: Number(heading.tagName.slice(1)),
        title,
        slug,
      });
    }
    return entries;
  }

  function decorateAlerts(root) {
    for (const quote of Array.from(root.querySelectorAll("blockquote"))) {
      const firstParagraph = quote.firstElementChild;
      if (!firstParagraph || firstParagraph.tagName !== "P") continue;

      const text = firstParagraph.textContent;
      const match = /^\s*\[!(NOTE|TIP|IMPORTANT|WARNING|CAUTION)\]\s*(?:\n|$)/.exec(text);
      if (!match) continue;

      const kind = match[1];
      const descriptor = ALERT_TYPES[kind];

      // Remove the marker text without touching any other inline content.
      const walker = document.createTreeWalker(firstParagraph, NodeFilter.SHOW_TEXT);
      let remaining = match[0].length;
      const nodes = [];
      while (walker.nextNode()) nodes.push(walker.currentNode);
      for (const node of nodes) {
        if (remaining <= 0) break;
        const take = Math.min(remaining, node.data.length);
        node.data = node.data.slice(take);
        remaining -= take;
      }
      if (firstParagraph.textContent.trim().length === 0) {
        firstParagraph.remove();
      } else {
        firstParagraph.firstChild &&
          (firstParagraph.firstChild.nodeType === Node.TEXT_NODE) &&
          (firstParagraph.firstChild.data = firstParagraph.firstChild.data.replace(/^\n/, ""));
      }

      const alert = document.createElement("div");
      alert.className = `md-alert md-alert-${kind.toLowerCase()}`;
      alert.setAttribute("role", "note");

      const title = document.createElement("p");
      title.className = "md-alert-title";

      const icon = document.createElement("span");
      icon.className = "md-alert-icon";
      icon.setAttribute("aria-hidden", "true");
      icon.textContent = descriptor.symbol;
      title.appendChild(icon);

      const label = document.createElement("span");
      label.className = "md-alert-label";
      label.textContent = descriptor.label;
      title.appendChild(label);

      alert.setAttribute("aria-label", descriptor.label);
      alert.appendChild(title);
      while (quote.firstChild) alert.appendChild(quote.firstChild);
      quote.replaceWith(alert);
    }
  }

  function decorateTaskLists(root) {
    for (const input of root.querySelectorAll("input")) {
      if ((input.getAttribute("type") || "").toLowerCase() !== "checkbox") {
        input.remove();
        continue;
      }

      const checked = input.hasAttribute("checked");
      for (const attribute of Array.from(input.attributes)) {
        input.removeAttribute(attribute.name);
      }
      input.setAttribute("type", "checkbox");
      // Markdown source stays authoritative: the preview never mutates text.
      input.setAttribute("disabled", "");
      input.setAttribute("aria-readonly", "true");
      if (checked) input.setAttribute("checked", "");
      input.setAttribute("aria-label", checked ? "Completed task" : "Incomplete task");

      const item = input.closest("li");
      if (item) {
        item.classList.add("md-task-item");
        item.setAttribute("data-md-task", checked ? "done" : "open");
        const list = item.parentElement;
        if (list && (list.tagName === "UL" || list.tagName === "OL")) {
          list.classList.add("md-task-list");
        }
      }
    }
  }

  function decorateFootnotes(root) {
    const section = root.querySelector("section.footnotes, section[data-footnotes]");
    if (section) {
      section.setAttribute("role", "doc-endnotes");
      section.classList.add("md-footnotes");
      if (!section.querySelector(".md-footnotes-title")) {
        const heading = document.createElement("h2");
        heading.className = "md-footnotes-title";
        heading.textContent = "Footnotes";
        heading.id = "user-content-footnotes";
        section.insertBefore(heading, section.firstChild);
        section.setAttribute("aria-labelledby", "user-content-footnotes");
      }
    }

    for (const anchor of root.querySelectorAll('a[href^="#footnote-"]')) {
      const href = anchor.getAttribute("href") || "";
      if (href.startsWith("#footnote-ref-")) {
        anchor.classList.add("md-footnote-backref");
        anchor.setAttribute("aria-label", "Back to reference");
      } else {
        anchor.classList.add("md-footnote-ref");
        anchor.setAttribute(
          "aria-label",
          `Footnote ${anchor.textContent.trim() || ""}`.trim()
        );
      }
    }
  }

  function languageOf(code) {
    for (const name of Array.from(code.classList)) {
      if (name.startsWith("language-")) {
        return name.slice("language-".length).toLowerCase();
      }
    }
    return "";
  }

  function decorateCodeBlocks(root) {
    const blocks = [];
    for (const code of root.querySelectorAll("pre > code")) {
      const pre = code.parentElement;
      const language = languageOf(code);
      if (CAPABILITIES.mermaid && language === "mermaid") {
        blocks.push({ code, pre, language });
        continue;
      }

      // The exact fence content is captured before any highlighter runs so Copy
      // always yields source text rather than highlighted markup.
      const source = code.textContent;

      const figure = document.createElement("div");
      figure.className = "md-code";
      const toolbar = document.createElement("div");
      toolbar.className = "md-code-toolbar";

      const label = document.createElement("span");
      label.className = "md-code-language";
      label.textContent = language || "text";
      toolbar.appendChild(label);

      const actions = document.createElement("div");
      actions.className = "md-code-actions";

      const wrapButton = document.createElement("button");
      wrapButton.type = "button";
      wrapButton.className = "md-code-button";
      wrapButton.textContent = "Wrap";
      wrapButton.setAttribute("aria-pressed", "false");
      wrapButton.addEventListener("click", () => {
        const wrapped = figure.classList.toggle("md-code-wrapped");
        wrapButton.setAttribute("aria-pressed", wrapped ? "true" : "false");
      });
      actions.appendChild(wrapButton);

      const lineCount = source.replace(/\n$/, "").split("\n").length;
      if (lineCount > 1 && lineCount <= LIMITS.maxLineNumbers) {
        const numbersButton = document.createElement("button");
        numbersButton.type = "button";
        numbersButton.className = "md-code-button";
        numbersButton.textContent = "Lines";
        numbersButton.setAttribute("aria-pressed", "false");
        numbersButton.addEventListener("click", () => {
          const on = figure.classList.toggle("md-code-numbered");
          numbersButton.setAttribute("aria-pressed", on ? "true" : "false");
          if (on && !figure.querySelector(".md-code-gutter")) {
            const gutter = document.createElement("pre");
            gutter.className = "md-code-gutter";
            gutter.setAttribute("aria-hidden", "true");
            const digits = [];
            for (let index = 1; index <= lineCount; index += 1) digits.push(index);
            gutter.textContent = digits.join("\n");
            pre.parentElement.insertBefore(gutter, pre);
          }
        });
        actions.appendChild(numbersButton);
      }

      const copyButton = document.createElement("button");
      copyButton.type = "button";
      copyButton.className = "md-code-button md-code-copy";
      copyButton.textContent = "Copy";
      const status = document.createElement("span");
      status.className = "md-code-status";
      status.setAttribute("role", "status");
      status.setAttribute("aria-live", "polite");
      copyButton.addEventListener("click", () => {
        if (source.length > LIMITS.maxCopyLength) {
          status.textContent = "Too large to copy";
          return;
        }
        post("clipboardHandler", { text: source });
        status.textContent = "Copied";
        window.setTimeout(() => {
          status.textContent = "";
        }, 1600);
      });
      actions.appendChild(copyButton);
      actions.appendChild(status);
      toolbar.appendChild(actions);

      pre.replaceWith(figure);
      figure.appendChild(toolbar);
      const body = document.createElement("div");
      body.className = "md-code-body";
      body.appendChild(pre);
      figure.appendChild(body);

      blocks.push({ code, pre, language, source });
    }
    return blocks;
  }

  function decorateImages(root) {
    for (const image of root.querySelectorAll("img[src]")) {
      image.classList.add("md-image");
      image.setAttribute("tabindex", "0");
      image.setAttribute("role", "button");
      const alt = image.getAttribute("alt") || "";
      image.setAttribute(
        "aria-label",
        alt ? `${alt} — activate to inspect` : "Image — activate to inspect"
      );
      image.addEventListener("click", () => window.__mdviewerOpenImageViewer(image));
      image.addEventListener("keydown", (event) => {
        if (event.key === "Enter" || event.key === " ") {
          event.preventDefault();
          window.__mdviewerOpenImageViewer(image);
        }
      });
    }
  }

  /* --------------------------------------------------------- Lite Prism */

  function highlightWithPrism(blocks) {
    if (!window.Prism || typeof window.Prism.highlight !== "function") return;

    for (const block of blocks) {
      const { code, language, source } = block;
      if (!language || source === undefined) continue;
      if (source.length > LIMITS.maxHighlightedCodeLength) continue;

      const grammarName = window.__mdviewerPrismAlias(language);
      const grammar = window.Prism.languages[grammarName];
      if (!grammar) continue;

      let html;
      try {
        html = window.Prism.highlight(source, grammar, grammarName);
      } catch {
        continue; // Plain text stays in place when highlighting fails.
      }

      const fragment = window.__mdviewerSanitizeHighlight(html);
      if (fragment) code.replaceChildren(fragment);
    }
  }

  /**
   * Highlighter output is sanitized by a dedicated policy that permits only
   * `span` with token class names. The Markdown allowlist is never widened.
   */
  window.__mdviewerSanitizeHighlight = function (html) {
    const fragment = DOMPurify.sanitize(html, {
      ALLOWED_TAGS: ["span"],
      ALLOWED_ATTR: ["class"],
      ALLOW_ARIA_ATTR: false,
      ALLOW_DATA_ATTR: false,
      RETURN_DOM_FRAGMENT: true,
    });
    for (const span of fragment.querySelectorAll("span")) {
      const kept = Array.from(span.classList).filter((name) =>
        /^(?:token|hljs|hljs-[a-z0-9_-]{1,32}|[a-z0-9_-]{1,32})$/.test(name)
      );
      span.removeAttribute("class");
      if (kept.length > 0) span.className = kept.join(" ");
    }
    return fragment;
  };

  window.__mdviewerPrismAlias = function (language) {
    switch (language) {
      case "js":
      case "jsx":
      case "node":
        return "javascript";
      case "ts":
      case "tsx":
        return "typescript";
      case "sh":
      case "zsh":
      case "shell":
        return "bash";
      case "py":
        return "python";
      case "rs":
        return "rust";
      case "html":
      case "xml":
      case "svg":
        return "markup";
      case "yml":
        return "yaml";
      default:
        return language;
    }
  };

  /* ------------------------------------------------------------ image zoom */

  const viewer = {
    overlay: null,
    image: null,
    scale: 1,
    offsetX: 0,
    offsetY: 0,
    restoreFocus: null,
  };

  function applyViewerTransform() {
    if (!viewer.image) return;
    viewer.image.style.transform =
      `translate(${viewer.offsetX}px, ${viewer.offsetY}px) scale(${viewer.scale})`;
  }

  function closeImageViewer() {
    if (!viewer.overlay) return;
    viewer.overlay.remove();
    viewer.overlay = null;
    viewer.image = null;
    if (viewer.restoreFocus && document.contains(viewer.restoreFocus)) {
      viewer.restoreFocus.focus();
    }
    viewer.restoreFocus = null;
  }

  window.__mdviewerOpenImageViewer = function (sourceImage) {
    if (viewer.overlay) closeImageViewer();
    if (!sourceImage || !sourceImage.getAttribute("src")) return;

    viewer.restoreFocus = document.activeElement;
    viewer.scale = 1;
    viewer.offsetX = 0;
    viewer.offsetY = 0;

    const overlay = document.createElement("div");
    overlay.className = "md-image-viewer";
    overlay.setAttribute("role", "dialog");
    overlay.setAttribute("aria-modal", "true");
    const alt = sourceImage.getAttribute("alt") || "";
    overlay.setAttribute("aria-label", alt ? `Image: ${alt}` : "Image viewer");
    overlay.tabIndex = -1;

    const stage = document.createElement("div");
    stage.className = "md-image-stage";

    const image = document.createElement("img");
    // Reuses the same already-authorized confined resource URL; no new access.
    image.setAttribute("src", sourceImage.getAttribute("src"));
    image.setAttribute("alt", alt);
    image.className = "md-image-full";
    image.draggable = false;
    stage.appendChild(image);

    const bar = document.createElement("div");
    bar.className = "md-image-controls";

    const makeButton = (text, label, action) => {
      const button = document.createElement("button");
      button.type = "button";
      button.className = "md-image-button";
      button.textContent = text;
      button.setAttribute("aria-label", label);
      button.addEventListener("click", action);
      return button;
    };

    const zoomBy = (factor) => {
      viewer.scale = Math.min(Math.max(viewer.scale * factor, 0.1), 12);
      applyViewerTransform();
    };
    bar.appendChild(makeButton("−", "Zoom out", () => zoomBy(1 / 1.25)));
    bar.appendChild(makeButton("+", "Zoom in", () => zoomBy(1.25)));
    bar.appendChild(
      makeButton("Fit", "Fit image to window", () => {
        viewer.scale = 1;
        viewer.offsetX = 0;
        viewer.offsetY = 0;
        stage.classList.remove("md-image-actual");
        applyViewerTransform();
      })
    );
    bar.appendChild(
      makeButton("1:1", "Show actual size", () => {
        viewer.scale = 1;
        viewer.offsetX = 0;
        viewer.offsetY = 0;
        stage.classList.add("md-image-actual");
        applyViewerTransform();
      })
    );
    const closeButton = makeButton("Close", "Close image viewer", closeImageViewer);
    bar.appendChild(closeButton);

    if (alt) {
      const caption = document.createElement("p");
      caption.className = "md-image-caption";
      caption.textContent = alt;
      overlay.appendChild(caption);
    }

    overlay.appendChild(stage);
    overlay.appendChild(bar);

    let dragging = false;
    let originX = 0;
    let originY = 0;
    stage.addEventListener("pointerdown", (event) => {
      dragging = true;
      originX = event.clientX - viewer.offsetX;
      originY = event.clientY - viewer.offsetY;
      stage.setPointerCapture(event.pointerId);
    });
    stage.addEventListener("pointermove", (event) => {
      if (!dragging) return;
      viewer.offsetX = event.clientX - originX;
      viewer.offsetY = event.clientY - originY;
      applyViewerTransform();
    });
    const endDrag = (event) => {
      dragging = false;
      if (stage.hasPointerCapture && event.pointerId !== undefined) {
        try {
          stage.releasePointerCapture(event.pointerId);
        } catch {
          /* pointer already released */
        }
      }
    };
    stage.addEventListener("pointerup", endDrag);
    stage.addEventListener("pointercancel", endDrag);
    stage.addEventListener(
      "wheel",
      (event) => {
        event.preventDefault();
        zoomBy(event.deltaY < 0 ? 1.1 : 1 / 1.1);
      },
      { passive: false }
    );

    overlay.addEventListener("keydown", (event) => {
      switch (event.key) {
        case "Escape":
          event.preventDefault();
          closeImageViewer();
          break;
        case "+":
        case "=":
          event.preventDefault();
          zoomBy(1.25);
          break;
        case "-":
          event.preventDefault();
          zoomBy(1 / 1.25);
          break;
        case "0":
          event.preventDefault();
          viewer.scale = 1;
          viewer.offsetX = 0;
          viewer.offsetY = 0;
          applyViewerTransform();
          break;
        case "ArrowLeft":
          event.preventDefault();
          viewer.offsetX += 40;
          applyViewerTransform();
          break;
        case "ArrowRight":
          event.preventDefault();
          viewer.offsetX -= 40;
          applyViewerTransform();
          break;
        case "ArrowUp":
          event.preventDefault();
          viewer.offsetY += 40;
          applyViewerTransform();
          break;
        case "ArrowDown":
          event.preventDefault();
          viewer.offsetY -= 40;
          applyViewerTransform();
          break;
        default:
          break;
      }
    });
    overlay.addEventListener("click", (event) => {
      if (event.target === overlay) closeImageViewer();
    });

    document.body.appendChild(overlay);
    viewer.overlay = overlay;
    viewer.image = image;
    applyViewerTransform();
    overlay.focus();
  };

  window.__mdviewerCloseImageViewer = closeImageViewer;

  /* --------------------------------------------------------------- theming */

  window.applyTheme = function (theme) {
    if (!theme || (theme.category !== "light" && theme.category !== "dark")) {
      return false;
    }

    for (const token of Object.keys(themeProperties)) {
      const value = theme[token];
      if (typeof value !== "string" || !trustedColorPattern.test(value)) {
        return false;
      }
    }
    for (const [token, property] of Object.entries(themeProperties)) {
      document.documentElement.style.setProperty(property, theme[token]);
    }
    document.documentElement.style.colorScheme = theme.category;
    state.themeCategory = theme.category;
    if (window.__mdviewerFullThemeChanged) {
      window.__mdviewerFullThemeChanged(theme.category, state.generation);
    }
    return true;
  };

  /* ------------------------------------------------------------- pipeline */

  window.renderMarkdown = async function (markdown, printMode = false) {
    state.generation += 1;
    const generation = state.generation;
    window.markdownRenderCount = (window.markdownRenderCount || 0) + 1;
    state.printMode = printMode === true;
    state.lastMarkdown = String(markdown ?? "");
    document.documentElement.classList.toggle("print-mode", state.printMode);
    closeImageViewer();

    configureMarked();

    const separated = splitFrontmatter(state.lastMarkdown);
    let body = separated?.body ?? state.lastMarkdown;
    let frontmatter = null;
    if (separated && CAPABILITIES.frontmatter && window.__mdviewerReadFrontmatter) {
      const parsed = await window.__mdviewerReadFrontmatter(
        separated.source,
        separated.body
      );
      if (generation !== state.generation) return { cancelled: true };
      body = parsed.body;
      frontmatter = parsed.card;
    } else if (separated) {
      frontmatter = buildRawFrontmatter(separated.source);
    }

    const fragment = sanitizeMarkdownHTML(marked.parse(body));

    const outline = decorateHeadings(fragment);
    decorateAlerts(fragment);
    decorateTaskLists(fragment);
    decorateFootnotes(fragment);
    const codeBlocks = decorateCodeBlocks(fragment);
    decorateImages(fragment);

    const content = document.getElementById("content");
    content.replaceChildren();
    if (frontmatter) content.appendChild(frontmatter);
    content.appendChild(fragment);

    state.outline = outline;

    if (CAPABILITIES.prism) {
      highlightWithPrism(codeBlocks);
    } else if (CAPABILITIES.highlightJS && window.__mdviewerHighlightBlocks) {
      // Asynchronous and generation-guarded: a stale highlight never lands.
      window.__mdviewerHighlightBlocks(codeBlocks, generation);
    }

    if (CAPABILITIES.mermaid && window.__mdviewerRenderDiagrams) {
      window.__mdviewerRenderDiagrams(
        codeBlocks.filter((block) => block.language === "mermaid"),
        generation,
        state.printMode
      );
    }

    return {
      resources: Array.from(content.querySelectorAll("img[src]")).map((image) =>
        image.getAttribute("src")
      ),
      outline,
      height: document.body.scrollHeight,
      generation,
    };
  };

  window.mdviewerOutline = function () {
    return state.outline;
  };

  window.mdviewerRenderGeneration = function () {
    return state.generation;
  };

  function isSearchableTextNode(node, root) {
    if (!node || !node.data || node.data.length === 0) return false;

    let element = node.parentElement;
    while (element) {
      if (
        element.matches(
          "script,style,noscript,summary,button,input,textarea,select,option," +
            "[role='button'],[role='searchbox'],[contenteditable='true']"
        ) ||
        element.hidden ||
        element.getAttribute("aria-hidden") === "true"
      ) {
        return false;
      }

      const style = getComputedStyle(element);
      if (
        style.display === "none" ||
        style.visibility === "hidden" ||
        style.visibility === "collapse" ||
        Number.parseFloat(style.opacity) === 0
      ) {
        return false;
      }
      if (element === root) break;
      element = element.parentElement;
    }
    if (element !== root) return false;

    const range = document.createRange();
    range.selectNodeContents(node);
    return range.getClientRects().length > 0;
  }

  function searchFlowContainer(node, root) {
    let element = node.parentElement;
    while (element && element !== root) {
      const display = getComputedStyle(element).display;
      if (display !== "inline" && display !== "contents") return element;
      element = element.parentElement;
    }
    return root;
  }

  window.mdviewerCountMatches = function (query) {
    const needle = String(query ?? "").toLowerCase();
    const root = document.getElementById("content");
    if (!root || needle.length === 0) return 0;

    const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT, {
      acceptNode(node) {
        return isSearchableTextNode(node, root)
          ? NodeFilter.FILTER_ACCEPT
          : NodeFilter.FILTER_REJECT;
      },
    });
    const chunks = [];
    let previousContainer = null;
    while (walker.nextNode()) {
      const node = walker.currentNode;
      const container = searchFlowContainer(node, root);
      if (previousContainer && previousContainer !== container) chunks.push("\n");
      chunks.push(node.data);
      previousContainer = container;
    }

    const text = chunks.join("").toLowerCase();
    let count = 0;
    let offset = 0;
    while (offset <= text.length - needle.length) {
      const match = text.indexOf(needle, offset);
      if (match < 0) break;
      count += 1;
      offset = match + needle.length;
    }
    return count;
  };

  window.mdviewerScrollToSlug = function (slug) {
    const target = document.getElementById(String(slug));
    if (!target) return false;
    target.scrollIntoView({ block: "start" });
    target.setAttribute("tabindex", "-1");
    target.focus({ preventScroll: true });
    return true;
  };

  /**
   * Forces every lazy renderer to finish and waits for stable layout so print
   * output never captures a half-rendered page.
   */
  window.waitForResources = async function (timeoutMilliseconds = 8000) {
    const deadline = Date.now() + timeoutMilliseconds;

    if (window.__mdviewerPreparePrint) {
      await window.__mdviewerPreparePrint(state.generation, deadline);
    }

    const images = Array.from(document.images);
    await Promise.all(
      images.map((image) => {
        if (image.complete) return Promise.resolve();
        return new Promise((resolve) => {
          const finish = () => resolve();
          image.addEventListener("load", finish, { once: true });
          image.addEventListener("error", finish, { once: true });
          window.setTimeout(finish, Math.max(0, deadline - Date.now()));
        });
      })
    );

    await new Promise((resolve) => {
      let completed = false;
      const finish = () => {
        if (completed) return;
        completed = true;
        resolve();
      };
      // Offscreen print WKWebViews can throttle animation frames entirely.
      // The timer guarantees progress while the double frame still provides
      // stable layout for visible previews.
      window.setTimeout(finish, 60);
      requestAnimationFrame(() => requestAnimationFrame(finish));
    });
    return true;
  };

  window.mdviewerCapabilities = function () {
    return CAPABILITIES;
  };

  window.__mdviewerInternals = {
    slugify,
    uniqueSlug,
    isSafeLink,
    isRelativeURL,
    splitFrontmatter,
    nonce: NONCE,
    limits: LIMITS,
    state,
  };
})();
